# Site settings
title: Rustifications
description: >
  My Rustic Ramblings
baseurl: "/" # should be / if you build a global github page (eg o0ignition0o.github.io)
url: "https://stevedonovan.github.io" # The blog url you want to choose (you can use a github.io one, or pick your own hosted url :))
logo: "https://www.rust-lang.org/logos/rust-logo-64x64-blk.png" # This one is used as blog logo
twitter_username: StevedInJoburg
github_username: stevedonovan

# Build settings
highlighter: rouge

root: "https://check-out-my-awesome-blog.org" # Not really sure this is useful, need to cross check with blog writers :)
